version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/prototype"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "cargo"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions"