[workspace]
members = [
    "core",
    "wgpu-test",
    "type-record",
]
exclude = [
    "octree-collisions-renderer",
    "bevy-orbit-controls",
]
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
