use ultraviolet::IVec3;
use ultraviolet::Isometry3;
use ultraviolet::Mat3;
use ultraviolet::Rotor3;
use ultraviolet::Vec3;
pub type FVec = Vec3;
pub type IVec = IVec3;
pub type Iso = Isometry3;
pub type Rot = Rotor3;
pub type Mat = Mat3;
