[package]
name = "autofactory"
version = "1.0.0"
authors = ["iMplode nZ <rg@youxplode.com>"]
license = "GPL-3.0-only"
build = "build.rs"
edition = "2018"
publish = false

[lib]
name = "autofactory"

[dependencies]
enum_dispatch = "0.3.4"
parking_lot = { version = "0.11.0", features = ["nightly"] }
ref_clone = "0.8.0"
[dependencies.bevy]
# git = "https://github.com/bevyengine/bevy"
version = "0.3.0"
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
