[package]
name = "type-record-test"
version = "1.0.0"
authors = ["iMplode nZ <rg@youxplode.com>"]
license = "ISC"
edition = "2018"
publish = false

[lib]
name = "type_record_test"

[dependencies]
type-record = { path = "../type-record" }
