[package]
name = "autofactory-prototype"
version = "1.0.0"
authors = ["iMplode nZ <rg@youxplode.com>"]
license = "GPL-3.0-only"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]
publish = false
default-run = "main"

[lib]
name = "autofactory_prototype"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "main"
path = "src/_main.rs"

[dependencies]
rand = "0.7.3"
floating-duration = "0.1.2"
parking_lot = { version = "0.11.0", features = ["nightly"] }
ref_clone = "0.7.0"
[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
