name: JavaScript

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '14'
    - name: Install PNPM
      run: sudo npm i -g pnpm
    - name: Install Dependencies
      run: pnpm i
    - name: Build
      run: cd test && pnpm run action-build