name: JavaScript

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: pnpm/action-setup@v1.2.0
      with:
        version: 5.10
    - name: Update PNPM If Necessary
      run: sudo pnpm i -g pnpm
    - name: Install Dependencies
      run: pnpm i
    - name: Build
      run: cd test && pnpm run action-build