name: Rust

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Detect if formatted
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args:  --manifest-path ./core/Cargo.toml -- --check
    - name: Lint files
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path ./core/Cargo.toml -- -D warnings
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Attempt build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features --manifest-path ./core/Cargo.toml
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast --manifest-path ./core/Cargo.toml
